### PR TITLE
Run tests three times (transpiled source, minified file and legacy file)

### PR DESCRIPTION
**Pull request by ephread**
Minor changes, to run the tests three time. Once for coverage, once on the default file and one last time on the legacy file.

This is a WIP, because I'd like to show off the coverage metrics. @y-lohse how do you feel about adding a coverage shield to the README and coverage checks for PR? Is there a specific service you like?

### CODE REVIEW

**Comment by y-lohse** [comment]
> how do you feel about adding a coverage shield to the README and coverage checks for PR?

Yep, that would be god, especially for PRs.

> Is there a specific service you like?

I like how [codecov](https://github.com/apps/codecov) looks but last time I tried it was a pain to set up. But I haven't really looked at other services to feel free to pick whatever you feel is best :)

**Comment by ephread** [comment]
> I like how codecov looks but last time I tried it was a pain to set up.

I tend to use codecov as well. Oh yeah, in fact, it just failed:
https://codecov.io/gh/y-lohse/inkjs/commit/5e1e850c36939d9cd4d9f1e847c5a19b411d9917

I'll investigate tomorrow!

**Comment by y-lohse** [comment]
> Since it's a PR, I wonder if the issue happens because there aren't any base commit to compare the coverage to.

Feel free to merge some experimental things if it helps. The changes to the test runners LGTM 👍

**Comment by ephread** [comment]
Cool! I’ll merge the PR as soon as possible and then create a new branch to investigate (if necessary).

**Pull request merged**
