### PR TITLE
test: recompile tests with inklecate 1.0.0

### PR DESCRIPTION
**Pull request by ephread**
There isn't really anything to review in this PR, I'm just trying to keep the noise low for the next ones.

### CODE REVIEW

**Comment by y-lohse** [comment]
Since I assume the tests are failing only due to the bumped ink version number, I wonder if we should also bump the version already, without doing the other changes in Story.ts, just in order to have the tests passing again?

**Comment by ephread** [comment]
> I wonder if we should also bump the version already, without doing the other changes in Story.ts, just in order to have the tests passing again?

Very good idea, I hadn't thought of this! I'll make the change.

**Comment by ephread** [comment]
It's updated. 93 out of the 238 tests are failing, but it's to be expected since the format changed.

**Comment by y-lohse** [comment]
Yup cool, looks good! I'm happy to merge this into the V1.0 branch to track progress in that regard, if that was your intended plan?

**Review by y-lohse — APPROVED** [review]

**Comment by ephread** [comment]
@y-lohse I originally wanted to merge all the test changes at once, but now that I think of it, having yet another intermediary branch is a bit overkill.

Happy to merge this in `v1.0` straight away!

**Pull request merged**
