### PR TITLE
fix: fix mistakes preventing tests from passing

### PR DESCRIPTION
**Pull request by ephread**
This PR contains minor fixes. Tests are all green now thanks to @smwhr!

### CODE REVIEW

**Comment by smwhr** [comment]
In case this is useful, below is the mininal test that fails.
It does not even involve flow, just saving while having threads in there.  
Same test pass in the current public implementation.

```
it("tests simple save / load minimally with threads", () => {
    
    loadStory("multi_flow_save_load_threads");
    
    expect(story.Continue()).toBe("Default line 1\n");
    story.ChoosePathString("red");

    expect(story.Continue()).toBe("Hello I'm red\n");
    expect(story.currentChoices[0].text).toBe("Thread 1 red choice");

    let saved = story.state.ToJson();
    story.ResetState();
    story.state.LoadJson(saved);

    expect(story.currentText).toBe("Hello I'm red\n");
    expect(story.currentChoices[0].text).toBe("Thread 1 red choice");

    story.ChooseChoiceIndex(0);
    expect(story.ContinueMaximally()).toBe(
      "Thread 1 red choice\nAfter thread 1 choice (red)\n"
    );

  });
```

For the record, the exception is raised when "ContinueMaximally" is invoked and is the following :

```
StoryException: Ink had 1 warning and . It is strongly suggested that you assign an error handler 
to story.onError. The first issue was: RUNTIME WARNING: (Ink Pointer -> thread1.1.0.s -- index 2): 
Variable not found: 'name'. Using default value of 0 (false). This can happen with temporary 
variables if the declaration hasn't yet been hit. Globals are always given a default value on load 
if a value doesn't exist in the save state.
```

In order to trace which of the "name" variable was not found (because everything it that inkfile is called `name`), I tinkered with the ink file, and this is this one (that I renamed `flufty` to trace it manually):

```
== thread1(flufty) ==
+ Thread 1 {flufty} choice
    -> thread1Choice(flufty)
```

**Comment by ephread** [comment]
Thanks to @smwhr the last test breaking the suite has been fixed 🎉. Thanks again for the fix!

Now we just need to look into why the JavaScript test fail, but it's likely to be a configuration issue.

**Comment by ephread** [comment]
@smwhr my bad, I had forgotten to rebuild before running them. Gosh, it's been a while. I clarified that in `CONTRIBUTING.md`.

**Comment by ephread** [comment]
@y-lohse you have the floor mate!

**Review by y-lohse — APPROVED** [review]
Yessss looking all good, thanks!

**Comment by y-lohse** [comment]
This "all checks have passed" is really satisfying 😁

**Pull request merged**
