### PR TITLE
variableChangedEventCallbacks now preserved when VariableState is copied

### PR DESCRIPTION
**Pull request by michael-badrobotgames**
This missing line was breaking the variable observers.

### CODE REVIEW

**Comment by y-lohse** [comment]
Thank you! I had a quick look yesterday and the change seems good, but I'll have a more in depth look soon. Have you looked if the disabled unit tests are running again by any chance?

**Comment by michael-badrobotgames** [comment]
Yes, with the fix the commented out tests now pass.

**Comment by y-lohse** [comment]
That's really great news :)

I started the review but might get interrupted, so I'll start posting stuff here, sorry for the noise.
The reference implementation [doesn't have this line](https://github.com/inkle/ink/blob/0.8.3/ink-engine-runtime/VariablesState.cs#L120) so… that's odd. Maybe C# did the copy in some other way?

**Comment by y-lohse** [comment]
Riiight, `variableChangedEventCallbacks` is inkjs specific. So the fix LGTM 👍

**Pull request merged**
