### PR TITLE
Made observer param in RemoveVariableObserver optional

### PR DESCRIPTION
**Pull request by michael-badrobotgames**
When passing in only a specific variable name with the observer set to null, the function will clear all observers for the given variable. 

Matching PR created for inkle/ink 

All tests passed.

### CODE REVIEW

**Comment by y-lohse** [comment]
Thanks! We'll wait to see what happens upstream before merging this PR :)

**Comment by michael-badrobotgames** [comment]
Cool. What's with the Travis CI build failing? Just curious if I did something wrong, I'm still relatively new to contributing to other people's repos

**Comment by ephread** [comment]
@michael-badrobotgames nothing wrong, it's just a tiny linting issue. It fails because there's a trailing whitespace in Story.ts 😉

https://travis-ci.org/y-lohse/inkjs/builds/547498955#L1064

We need to add a CONTRIBUTING document explaining all that stuff.

**Comment by ephread** [comment]
Seems this was merged quite a while ago in [upstream](https://github.com/inkle/ink/pull/532)! Are we happy to merge this if there's no conflicts @y-lohse?

**Comment by y-lohse** [comment]
Yep!

**Comment by ephread** [comment]
Superseded by #470

**Pull request closed without merging**
