### PR TITLE
Ink v1.0

### PR DESCRIPTION
**Pull request by y-lohse**
Implementing #836  — this is the branch we can code against while porting everything. I think it's probably easier to track advancement here rather than in the issue as well.

Diff link: https://github.com/inkle/ink/compare/0.9.0%E2%80%A6v1.0.0

- [x] Unit tests
- [x] CallStack
- [x] Choice
- [x] ChoicePoint
- [x] Container
- [x] ControlCommand
- [x] DebugMetadata
- [x] Divert
- [x] Error
- [x] Flow
- [x] Glue
- [x] INamedContent
- [x] InkList
- [x] JsonSerialisation
- [x] ListDefinition
- [x] ListDefinitionsOrigin
- [x] NativeFunctionCall
- [x] Object
- [x] Path
- [x] Pointer
- [ ] Profiler
- ~[ ] Properties/AssemblyInfo~
- [x] PushPop
- [x] SearchResult
- [x] SimpleJson
- [x] StatePatch
- [x] Story
- [x] StoryException
- [x] StoryState
- [x] StringJoinExtension
- [x] Tag
- [x] Value
- [x] VariableAssignment
- [x] VariableReference
- [x] VariablesState
- [x] Void

### CODE REVIEW

**Comment by y-lohse** [comment]
Well the good news is most of the files only changed visibility from `internal` to `public`, but we never bothered with the `internal` in the first place 😁 .

It looks like most other changes are also fairly minor, with the exception of Story and StoryState which will presumably require most work.

I'm going to start with the changes in Value, it introduces a new type that is needed ina  few other files.

**Comment by ephread** [comment]
@y-lohse Fantastic, so much progress already!

**Comment by ephread** [comment]
Let me work on `DebugMetadata`, `Error`, `Flow` and `InkList`. I'm grabbing stuff from the top now!

**Comment by ephread** [comment]
Next, I'm tackling `JsonSerialisation` & `NativeFunctionCall`.

`Profiler` can be ignored since it was never ported.

**Comment by ephread** [comment]
Working on `Story` now.

**Comment by y-lohse** [comment]
Wooof, what a streak :D I'll get to reviewing all the PRs, thanks!

**Comment by ephread** [comment]
I'm starting the work on `StoryState` now!

**Comment by ephread** [comment]
And… it seems we're done!

@y-lohse what's going to happen with the version number? Since it's 1.0 in upstream, is this going to bump inkjs all the way up to 2.0?

Regardless, let me know as soon as possible, I'll create a PR to update the compatibility table in the README.

**Comment by y-lohse** [comment]
> @y-lohse what's going to happen with the version number? Since it's 1.0 in upstream, is this going to bump inkjs all the way up to 2.0?

Yes let's go with that. The other option is to tag it as 1.12.0 (technically there is no breaking change) but it's probably cleaner to bump it up to v2.0.0.

> Regardless, let me know as soon as possible, I'll create a PR to update the compatibility table in the README.

Alright! I'll rebase this and… well I think we can merge it 🎉

**Comment by y-lohse** [comment]
@ephread I updated the table as part of https://github.com/y-lohse/inkjs/pull/877 :)

**Pull request merged**
